#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "phpldapadmin"
name = "phpLDAPadmin"
description.en = "Manage OpenLDAP database over the web"
description.fr = "Application web de gestion de la base OpenLDAP"

version = "2.0.2~ynh1"

maintainers = ["aymhce"]

[upstream]
license = "GPL-2.0-or-later"
website = "http://www.phpldapadmin.org"
demo = "https://olddemo.phpldapadmin.org/"
admindoc = "http://www.phpldapadmin.org"
code = "https://github.com/leenooks/phpLDAPadmin"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/phpldapadmin"

    [install.init_main_permission]
    type = "group"
    default = "admins"

    [install.admin]
    type = "user"

[resources]
    [resources.sources.main]
    url = "https://github.com/leenooks/phpLDAPadmin/archive/refs/tags/2.0.2.tar.gz"
    sha256 = "b9ad3b5c94b1ec68729ca24c321d112c030e32da63df65796dfd8edf136d6a17"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"

    [resources.apt]
    packages ='php8.4-ldap, php8.4-xml, php8.4-igbinary, php8.4-msgpack, php8.4-memcached, php8.4-sqlite3'
