packaging_format = 2

id = "phpldapadmin"
name = "phpLDAPadmin"
description.en = "Manage OpenLDAP database over the web"
description.fr = "Application web de gestion de la base OpenLDAP"

version = "2.0.0~ynh1"

maintainers = ["aymhce"]

[upstream]
license = "GPL-2.0-or-later"
website = "http://www.phpldapadmin.org"
demo = "https://olddemo.phpldapadmin.org/"
admindoc = "http://www.phpldapadmin.org"
code = "https://github.com/leenooks/phpLDAPadmin"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = true
sso =  false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/phpldapadmin"

    [install.init_main_permission]
    type = "group"
    default = "admins"

    [install.admin]
    type = "user"

[resources]
        [resources.sources.main]
        url = "https://github.com/leenooks/phpLDAPadmin/archive/refs/tags/2.0.0.tar.gz"
        sha256 = "9efe3e74c90c766a61c99e9e01923228b7c5dbc7761b1c2f5a92ef145c19eadd"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    main.allowed = "admins"

    [resources.apt]
    packages ='php7.4-ldap, php7.4-xml'
