#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# MODIFY URL IN NGINX CONF
#=================================================
ynh_script_progression "Updating NGINX web server configuration..."

# this will most likely adjust NGINX config correctly
ynh_config_change_url_nginx

#=================================================
# SPECIFIC MODIFICATIONS
#=================================================

ynh_replace --match="https://$old_domain$old_path" --replace="https://$new_domain$new_path" --file="$install_dir/.env"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Change of URL completed for $app"
