#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

# Create a PHP-FPM config (with conf/extra_php-fpm.conf being appended to it)
ynh_config_add_phpfpm

# Create a dedicated NGINX config using the conf/nginx.conf template
ynh_config_add_nginx

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

ynh_nodejs_install
ynh_composer_install
ynh_composer_exec install --optimize-autoloader --no-dev

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app npm install
	ynh_hide_warnings ynh_exec_as_app npm run prod
	ynh_hide_warnings ynh_exec_as_app php$php_version artisan key:generate --no-interaction --force
	ynh_hide_warnings ynh_exec_as_app php$php_version artisan optimize
	ynh_hide_warnings ynh_exec_as_app php$php_version artisan migrate --no-interaction --force
popd

ynh_backup_if_checksum_is_different "$install_dir/.env"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of $app completed"
