#!/bin/bash

set -eu

. /usr/share/yunohost/helpers
ynh_abort_if_errors

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get "$app" domain)
path=$(ynh_app_setting_get "$app" path)
admin=$(ynh_app_setting_get "$app" admin)

test ! -d /var/www/$app \
        || ynh_die "There is already a directory: /var/www/$app "

path=$(ynh_normalize_url_path $path)
#ynh_webpath_available $domain $path
#ynh_webpath_register $app $domain $path

sudo cp -a ./sources "/var/www/$app"

cp -a ./conf/nginx.conf "/etc/nginx/conf.d/$domain.d/$app.conf"

sudo service nginx reload
