#!/bin/bash

#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# ENSURE DOWNWARD COMPATIBILITY
#=================================================
ynh_script_progression "Ensuring downward compatibility..."

#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Upgrading source files..."

# Download, check integrity, uncompress and patch the source from manifest.toml
ynh_setup_source --dest_dir="$install_dir" --full_replace --keep=".env /database/database.sqlite"

#=================================================
# INSTALL APP
#=================================================
ynh_script_progression "Installing app..."

ynh_nodejs_install
ynh_composer_install
ynh_composer_exec install --optimize-autoloader --no-dev

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration files..."

if ynh_app_upgrading_from_version_before 2.0.0~ynh1; then
	pushd "$install_dir"
		app_key=$(ynh_hide_warnings ynh_exec_as_app php$php_version artisan key:generate --no-interaction --show)
		ynh_app_setting_set --key=app_key --value=$app_key
	popd
fi

ynh_config_add --template=".env" --destination="$install_dir/.env"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_phpfpm

ynh_config_add_nginx

#=================================================
# BUILD APP
#=================================================
ynh_script_progression "Building app..."

pushd "$install_dir"
	ynh_hide_warnings ynh_exec_as_app npm install
	ynh_hide_warnings ynh_exec_as_app npm run prod
	ynh_hide_warnings ynh_exec_as_app php$php_version artisan optimize
	ynh_hide_warnings ynh_exec_as_app php$php_version artisan migrate --no-interaction --force
popd

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
